# Generated by Django 4.2 on 2023-04-24 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_user_blog_author_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 4, 24, 5, 16, 57, 102143, tzinfo=datetime.timezone.utc)),
        ),
    ]
